### ISSUE TITLE
Runtime exception: java.lang.NoClassDefFoundError: com/sun/jersey/core/spi/factory/AbstractRuntimeDelegate

### ISSUE THREAD

**Issue by liosedhel** [FaKod/neo4j-scala#33]
This exception occurs when I switch from 0.3.0 to 0.3.1-SNAPSHOT (build taken from Sonatype repository) 
`scalaVersion = 2.10.4`

```
[info]   java.lang.NoClassDefFoundError: com/sun/jersey/core/spi/factory/AbstractRuntimeDelegate
[info]   at java.lang.ClassLoader.defineClass1(Native Method)
[info]   at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
[info]   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[info]   at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
[info]   at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
```

Test to reproduce:

``` scala
import eu.fakod.neo4jscala.{RestGraphDatabaseServiceProvider, Neo4jWrapper}
import org.scalatest.{Matchers, FlatSpec}
import java.net.URI

class Neo4jScalaBug extends FlatSpec with Matchers{

  class Neo4jDatabaseCreator extends Neo4jWrapper with RestGraphDatabaseServiceProvider {

    override def uri: URI = new URI("http://127.0.0.1:7474/db/data")
  }

  "Neo4jDatabaseCreateor" should "be instantiated properly" in {
    val dbCreator = new Neo4jDatabaseCreator
  }

}
```

**Comment by olahast** [comment]
This is simply due to missing "com.sun.jersey" % "jersey-core" % "1.9", dependency
